// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI8z92eO0dHZkgg8tOyPlwZyRlOAUKQmc',
    appId: '1:656249586379:web:199932e89c49087c0c114e',
    messagingSenderId: '656249586379',
    projectId: 'clean-architecture-chat-a6264',
    authDomain: 'clean-architecture-chat-a6264.firebaseapp.com',
    storageBucket: 'clean-architecture-chat-a6264.appspot.com',
    measurementId: 'G-S710J9ZT2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtwmexN8-64QOhdGC0z8KOLBfYllJpgs4',
    appId: '1:656249586379:android:be47548cc80c0ec90c114e',
    messagingSenderId: '656249586379',
    projectId: 'clean-architecture-chat-a6264',
    storageBucket: 'clean-architecture-chat-a6264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFjEHAlu-eeG1lCCO_t9MjlIxVC0RNBFE',
    appId: '1:656249586379:ios:81b80783964a48820c114e',
    messagingSenderId: '656249586379',
    projectId: 'clean-architecture-chat-a6264',
    storageBucket: 'clean-architecture-chat-a6264.appspot.com',
    iosClientId: '656249586379-ftdchv2q02sndioudh7li035l3vpk2bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFjEHAlu-eeG1lCCO_t9MjlIxVC0RNBFE',
    appId: '1:656249586379:ios:ae5a4f1d19ca42dd0c114e',
    messagingSenderId: '656249586379',
    projectId: 'clean-architecture-chat-a6264',
    storageBucket: 'clean-architecture-chat-a6264.appspot.com',
    iosClientId: '656249586379-tobhh1f1mahdaaicivrikbmtparot4tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
